# SPDX-FileCopyrightText: <text>Copyright 2021,2022 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is part of PAF, the Physical Attack Framework.

name: "Ubuntu 20.04 + gcc"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CMAKE_BUILD_TYPE: Debug
  CC: gcc
  CXX: g++

jobs:

  configure_build_test:
    name: "Install, configure, build and test"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: Install dependencies for apps with a GUI, doxygen and Ninja
      run: sudo apt-get install pkg-config libwxgtk3.0-gtk3-dev doxygen graphviz ninja-build
    - name: Configure
      run: CC=${{env.CC}} CXX=${{env.CXX}} cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE:STRING=${{env.CMAKE_BUILD_TYPE}} -DPAF_BUILD_DOCUMENTAION:BOOL=ON -G Ninja
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ninja test
    - name: Documentation
      working-directory: ${{github.workspace}}/build
      run: ninja doc
